### ISSUE TITLE
Webview desactivated

### ISSUE THREAD

**Issue by falconairex** [ingbrzy/MA-XML-10-BRAZILIAN#36]
Ifound this bug for any app to use webview
android.view.InflateException: Binary XML file line #30: Binary XML file line #30: Error inflating class com.android.mail.browse.ConversationWebView
Caused by: android.view.InflateException: Binary XML file line #30: Error inflating class com.android.mail.browse.ConversationWebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(Unknown Source:210)
	at android.view.LayoutInflater.createViewFromTag(Unknown Source:115)
	at android.view.LayoutInflater.createViewFromTag(Unknown Source:6)
	at android.view.LayoutInflater.rInflate(Unknown Source:92)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.rInflate(Unknown Source:103)
	at android.view.LayoutInflater.rInflateChildren(Unknown Source:9)
	at android.view.LayoutInflater.inflate(Unknown Source:124)
	at android.view.LayoutInflater.inflate(Unknown Source:20)
	at fog.run(Unknown Source:22)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:208)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getProviderClass(Unknown Source:175)
	at android.webkit.WebViewFactory.getProvider(Unknown Source:50)
	at android.webkit.WebView.getFactory(Unknown Source:0)
	at android.webkit.WebView.ensureProviderCreated(Unknown Source:7)
	at android.webkit.WebView.setOverScrollMode(Unknown Source:3)
	at android.view.View.<init>(Unknown Source:132)
	at android.view.View.<init>(Unknown Source:6)
	at android.view.ViewGroup.<init>(Unknown Source:0)
	at android.widget.AbsoluteLayout.<init>(Unknown Source:0)
	at android.webkit.WebView.<init>(Unknown Source:0)
	at android.webkit.WebView.<init>(Unknown Source:7)
	at android.webkit.WebView.<init>(Unknown Source:1)
	at android.webkit.WebView.<init>(Unknown Source:3)
	at eab.<init>(SourceFile:4)
	at dep.<init>(SourceFile:2)
	at com.android.mail.browse.ConversationWebView.<init>(SourceFile:2)
	... 19 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(Unknown Source:60)
	at android.webkit.WebViewFactory.getProviderClass(Unknown Source:12)
	... 34 more

**Comment by ingbrzy** [comment]
Not a translation issue..
